services:
  zabbix-postgres:
    image: postgres:14
    container_name: zabbix-postgres
    environment:
      POSTGRES_DB: ${ZBX_DB_NAME}
      POSTGRES_USER: ${ZBX_DB_USER}
      POSTGRES_PASSWORD: ${ZBX_DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: ${ZBX_DB_HOST}
      POSTGRES_USER: ${ZBX_DB_USER}
      POSTGRES_PASSWORD: ${ZBX_DB_PASS}
    depends_on:
      - zabbix-postgres
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: ${ZBX_DB_HOST}
      POSTGRES_USER: ${ZBX_DB_USER}
      POSTGRES_PASSWORD: ${ZBX_DB_PASS}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Africa/Abidjan
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      - |
        grafana cli plugins install alexanderzobnin-zabbix-app && \
        /run.sh

volumes:
  pgdata:
  grafana-storage:
